title: PASTA
description: PHP Alert for Spaghetti Twisted Architecture
baseurl: "/pasta-lunch"
url: "https://koriym.github.io"
theme: minima
github:
  repository_url: https://github.com/koriym/pasta-lunch

header_pages: []

defaults:
  - scope:
      path: "issues"
    values:
      nav_exclude: true
